adding ssl/tls example
qweeze/rstream pull request #108
Opened 2023-07-24 12:30 UTC by DanielePalaia

Adding a ssl/tls example, it seems like the old one was deprecated and not working.

2023-07-24 13:48 UTC, Gsantomaggio requested changes

2023-07-24 13:48 UTC, Gsantomaggio commented on docs/examples/tls/producer.py
> +        "/Users/dpalaia/projects/rabbitmq-stream-go-client/compose/tls/tls-gen/basic/result/ca_certificate.pem"
I'd avoid putting all the paths here.
```
/Users/dpalaia/projects/rabbitmq-stream-go-client/compose/tls/tls-gen/basic/result/ca_certificate.pem 
```

maybe only a relative path

2023-07-24 13:53 UTC, DanielePalaia commented on docs/examples/tls/producer.py
> +        "/Users/dpalaia/projects/rabbitmq-stream-go-client/compose/tls/tls-gen/basic/result/ca_certificate.pem"
Yeah I agree let me remove it

2023-07-25 08:12 UTC, Gsantomaggio approved these changes

2023-07-25 08:24 UTC, merged